name: gitjournal
description: A Note Taking App Built on top of Git
version: 1.89.0+10

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.2"

publish_to: none

dependencies:
  android_x_storage: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^3.1.2
  buffer: ^1.2.0
  carousel_slider: ^5.0.0
  collection: ^1.15.0-nullsafety.4
  community_material_icon: ^5.9.55
  connectivity_plus: ^6.1.4
  convert: ^3.1.1
  crypto: ^3.0.2
  cryptography: ^2.0.5
  dart_date: ^1.1.1
  dart_git:
    git: https://github.com/GitJournal/dart-git.git
    # path: ../gitjournal/dart-git
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  email_validator: ^3.0.0
  equatable: ^2.0.0
  file_picker: ^10.2.0
  fimber: ^0.7.0
  fixnum: ^1.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_displaymode: ^0.6.0
  flutter_email_sender: ^7.0.0
  flutter_emoji: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  flutter_tex_js: ^5.0.0
  font_awesome_flutter: ^10.0.0
  function_types: ^0.1.0
  go_git_dart:
    git: https://github.com/GitJournal/go_git_dart.git
  git_setup:
    path: packages/git_setup
  google_api_availability: ^5.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  http: ^1.4.0
  icloud_documents_path:
    git: https://github.com/GitJournal/icloud_documents_path.git
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+2
  intl: ^0.20.2
  language_picker: ^0.4.1
  launch_app_store: ^1.1.2
  markdown: ^7.2.2
  mutex: ^3.0.0
  nested: ^1.0.0
  openssh_ed25519:
    git: https://github.com/GitJournal/openssh_ed25519.git
  org_flutter: ^9.8.0
  package_info_plus: ^8.3.0
  path: ^1.8.0
  path_provider: ^2.0.11
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  protobuf: ^4.1.0
  provider: ^6.0.1
  quick_actions: ^1.0.6
  quiver: ^3.2.1
  recase: ^4.0.0
  receive_sharing_intent: ^1.4.5
  sentry_flutter: ^9.1.0
  share_plus: ^11.0.0
  shared_preferences: ^2.0.5
  sprintf: ^7.0.0
  stack_trace: ^1.11.1
  synchronized: ^3.0.0
  time: ^2.0.0
  timeago: ^3.1.0
  tuple: ^2.0.1
  universal_io: ^2.0.4
  url_launcher: ^6.0.3
  uuid: ^4.2.1
  yaml: ^3.1.0
  yaml_serializer: ^0.0.12
  archive: ^3.6.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  supabase_flutter: ^2.6.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner:
  flutter_launcher_icons:
    git: https://github.com/dirkbo/flutter_launcher_icons
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  process_run: ^1.2.4
  test:
  widgetbook:
    git:
      url: https://github.com/devfelipereis/widgetbook
      ref: upgrade-flutter-3.10
      path: packages/widgetbook

flutter:
  uses-material-design: true
  generate: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/OnBoardingMarkdown.png"
    - "assets/OnBoardingGitProviders.png"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  ios: true
  macos: true
  windows: false
  linux: false
